FROM ghcr.io/tenstorrent/tt-inference-server/vllm-tt-metal-src-dev-ubuntu-22.04-amd64:0.15.0-a247a5208f1ff49a209ceb3b388b45d174a5f639-8f3691068e95725629d0d9118a11c6450284c451
COPY --chown=container_app_user:container_app_user tt-vllm-plugin /home/container_app_user/tt-vllm-plugin
RUN /home/container_app_user/tt-metal/python_env/bin/pip install --no-deps -e /home/container_app_user/tt-vllm-plugin  && /home/container_app_user/tt-metal/python_env/bin/python -c "import tt_vllm_plugin; print('tt_vllm_plugin import OK')"
