apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: wan2.2-t2v-a14b-galaxy-
resources:
  - ../../base/media
  - secret.yaml
images:
  - name: ghcr.io/tenstorrent/tt-media-inference-server
    newTag: 0.10.0-555f240
patches:
  - path: patch-deployment.yaml
  - path: patch-configmap.yaml
  - patch: |
      - op: remove
        path: /spec/template/spec/containers/0/livenessProbe
      - op: remove
        path: /spec/template/spec/containers/0/readinessProbe
    target:
      kind: Deployment
      name: tt-inference-server
