apiVersion: apps/v1
kind: Deployment
metadata:
  name: tt-inference-server
spec:
  template:
    spec:
      containers:
        - name: inference-server
          resources:
            limits:
              memory: 200Gi
            requests:
              memory: 100Gi
      volumes:
        - name: cache
          hostPath:
            path: /opt/cache/Wan2.2-T2V-A14B-Diffusers-galaxy
