apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: mochi-1-preview-galaxy-
resources:
  - ../../base/media
images:
  - name: ghcr.io/tenstorrent/tt-media-inference-server
    newTag: 0.10.0-555f240
patches:
  - path: patch-deployment.yaml
  - path: patch-configmap.yaml
secretGenerator:
  - name: tt-inference-server
    envs:
      - ../../hf-token.env
    options:
      disableNameSuffixHash: true
