apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: distil-whisper-large-v3-galaxy-
resources:
  - ../../base/media
  - secret.yaml
images:
  - name: ghcr.io/tenstorrent/tt-media-inference-server
    newTag: 0.11.1-bac8b34
patches:
  - path: patch-deployment.yaml
  - path: patch-configmap.yaml
