services:
  inference_server:
    image: ghcr.io/tenstorrent/tt-inference-server/tt-metal-yolov4-src-base:${IMAGE_VERSION}-tt-metal-${TT_METAL_COMMIT_DOCKER_TAG}
    build:
      context: .
      dockerfile: yolov4.src.Dockerfile
      args:
        TT_METAL_DOCKERFILE_VERSION: ${TT_METAL_DOCKERFILE_VERSION}
        TT_METAL_COMMIT_SHA_OR_TAG: ${TT_METAL_COMMIT_SHA_OR_TAG}
    container_name: inference_server
    ports:
      - "7001:7000"
    devices:
      - "/dev/tenstorrent/1:/dev/tenstorrent/1"
    networks:
      - tt_studio_network
    volumes:
      - "/dev/hugepages-1G/:/dev/hugepages-1G:rw"
    shm_size: "32G"
    cap_add:
      - ALL
    stdin_open: true
    tty: true
    # this is redundant as docker compose automatically uses the .env file as its in the same directory
    # but this explicitly demonstrates its usage
    env_file:
      - .env.default
    restart: no

networks:
  tt_studio_network:
    # need external flag to allow for the backend to manage the docker network
    # otherwise, docker compose will create an app_* network for the backend container
    # to avoid colliding existing docker networks
    external: true
    name: tt_studio_network
