apiVersion: apps/v1
kind: Deployment
metadata:
  name: tt-inference-server
spec:
  template:
    spec:
      containers:
        - name: inference-server
          args:
            - "--model"
            - "gpt-oss-120b"
            - "--tt-device"
            - "galaxy"
          resources:
            limits:
              memory: 512Gi
            requests:
              memory: 300Gi
          livenessProbe:
            initialDelaySeconds: 7200
            periodSeconds: 30
          readinessProbe:
            initialDelaySeconds: 7200
            periodSeconds: 10
      volumes:
        - name: cache
          hostPath:
            path: /opt/cache/gpt-oss-120b-galaxy
