apiVersion: apps/v1
kind: Deployment
metadata:
  name: tt-inference-server
spec:
  template:
    spec:
      containers:
        - name: inference-server
          resources:
            limits:
              memory: 480Gi
            requests:
              memory: 200Gi
      volumes:
        - name: cache
          hostPath:
            path: /opt/cache/stable-diffusion-xl-base-1.0-galaxy
