apiVersion: v1
kind: Secret
metadata:
  name: {{ include "tt-inference-server.secretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "tt-inference-server.labels" . | nindent 4 }}
type: Opaque
{{- if .Values.hfToken }}
stringData:
  HF_TOKEN: {{ .Values.hfToken | quote }}
{{- end }}
