#!/bin/bash
# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: © 2025 Tenstorrent USA, Inc.
#
# Unified Blaze build: builds everything needed to run the C++ media server
# with the real decode scheduler from tt-llm-engine.
#
# Mirrors Dockerfile.blaze but runs locally. Steps:
#   1. init the tt-llm-engine submodule (+ tt-metal)
#   2. build tt-metal and create its python_env
#   3. build tt-llm-engine with metal backend -> tt-llm-engine/build-full/libtt_llm_engine.so
#   4. build the C++ server with --blaze (links against tt-metal)
#
# Re-running is cheap: each step is skipped if its output already exists.
# Use --fresh-engine to force a rebuild of tt-metal + tt-llm-engine.
#
# Usage:
#   ./build_blaze.sh
#   ./build_blaze.sh --fresh-engine
#
# After building, run the server with:
#   export LD_LIBRARY_PATH="$(pwd)/tt-llm-engine/tt-metal/build/lib:$LD_LIBRARY_PATH"
#   LD_PRELOAD="$(pwd)/tt-llm-engine/build-full/libtt_llm_engine.so.0" \
#     ./build/tt_media_server_cpp

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ENGINE_DIR="${SCRIPT_DIR}/tt-llm-engine"
export TT_METAL_HOME="${ENGINE_DIR}/tt-metal"
export PYTHON_ENV_DIR="${TT_METAL_HOME}/python_env"

FRESH_ENGINE=0
[ "${1:-}" = "--fresh-engine" ] && FRESH_ENGINE=1

# tokenizers-cpp (built by both tt-llm-engine and the cpp_server) pulls Rust
# crates (rayon) that require rustc >= 1.80. The system rustc on exabox nodes
# is often too old (e.g. 1.75), and the child build scripts only fall back to
# ~/.cargo when cargo is *entirely* missing — so a too-old system cargo wins.
# Prefer a rustup toolchain in ~/.cargo and, like Dockerfile.blaze, install one
# automatically when Rust is absent or too old.
_activate_rust() {
    [ -d "${HOME}/.cargo/bin" ] && export PATH="${HOME}/.cargo/bin:${PATH}"
    if ! command -v cargo >/dev/null 2>&1 && [ -f "${HOME}/.cargo/env" ]; then
        # shellcheck source=/dev/null
        . "${HOME}/.cargo/env"
    fi
}
_rustc_recent() {  # success iff rustc >= 1.80
    local ver major minor
    ver="$(rustc --version 2>/dev/null | awk '{print $2}')"
    [ -n "${ver}" ] || return 1
    major="${ver%%.*}"; minor="${ver#*.}"; minor="${minor%%.*}"
    [ "${major}" -gt 1 ] || { [ "${major}" -eq 1 ] && [ "${minor}" -ge 80 ]; }
}

_activate_rust
if ! _rustc_recent; then
    echo "=== Installing rustup stable (no system rustc >= 1.80 found) ==="
    export CARGO_HOME="${HOME}/.cargo" RUSTUP_HOME="${HOME}/.rustup"
    # --no-modify-path: we manage PATH above. -y continues past the harmless
    # "Rust is already installed" warning when a system rustc is present.
    curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs \
        | sh -s -- -y --default-toolchain stable --profile minimal --no-modify-path
    _activate_rust
fi
if ! _rustc_recent; then
    echo "ERROR: rustc >= 1.80 required for tokenizers-cpp, but install/activation failed."
    echo "  Try manually: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs \\"
    echo "    | sh -s -- -y --default-toolchain stable --no-modify-path"
    exit 1
fi
echo "Using rustc $(rustc --version | awk '{print $2}') ($(command -v rustc))"

# ── 1. tt-llm-engine submodule (+ tt-metal) ──────────────────────────────
if [ ! -f "${TT_METAL_HOME}/CMakeLists.txt" ]; then
    echo "=== Initializing tt-llm-engine submodule ==="
    git -C "${SCRIPT_DIR}" submodule update --init --recursive tt-llm-engine
    git -C "${ENGINE_DIR}" submodule update --init --recursive
fi

# ── 2. tt-metal + python_env ─────────────────────────────────────────────
# Sentinel: build_metal.sh produces build/lib/libtt_metal.so (build is a
# symlink to build_<CONFIG>). tt-metaliumConfig.cmake is NOT generated by the
# default build, so don't use it as the skip-check.
METAL_LIB="${TT_METAL_HOME}/build/lib/libtt_metal.so"
if [ "${FRESH_ENGINE}" = 1 ] || [ ! -f "${METAL_LIB}" ]; then
    echo "=== Building tt-metal ==="
    (cd "${TT_METAL_HOME}" && ./build_metal.sh --disable-profiler)
fi
if [ ! -d "${PYTHON_ENV_DIR}" ]; then
    echo "=== Creating tt-metal python_env ==="
    (cd "${TT_METAL_HOME}" && ./create_venv.sh)
fi

# ── 3. tt-llm-engine (with metal backend) ────────────────────────────────
if [ "${FRESH_ENGINE}" = 1 ] || [ ! -f "${ENGINE_DIR}/build-full/libtt_llm_engine.so" ]; then
    echo "=== Building tt-llm-engine (--ds-full) ==="
    (cd "${ENGINE_DIR}" && ./setup.sh --ds-full)
fi

# ── 4. C++ media server (--blaze) ────────────────────────────────────────
# Drogon + jsoncpp + libuuid are not system-installed on exabox nodes; they
# live in a persistent node-local prefix (built once via
# `./build_exabox.sh --install-deps`, which survives across compute nodes).
# Make that prefix visible to CMake (find_package), pkg-config, and the linker.
LOCAL_PREFIX="${LOCAL_PREFIX:-/data/${USER}/.local}"
if [ -f "${LOCAL_PREFIX}/lib/cmake/Drogon/DrogonConfig.cmake" ]; then
    echo "Using node-local dependency prefix: ${LOCAL_PREFIX} (Drogon, jsoncpp, uuid)"
    export CMAKE_PREFIX_PATH="${LOCAL_PREFIX}:${CMAKE_PREFIX_PATH:-}"
    export PKG_CONFIG_PATH="${LOCAL_PREFIX}/lib/pkgconfig:${LOCAL_PREFIX}/share/pkgconfig:${PKG_CONFIG_PATH:-}"
    export LD_LIBRARY_PATH="${LOCAL_PREFIX}/lib:${LD_LIBRARY_PATH:-}"
elif ! pkg-config --exists drogon 2>/dev/null \
     && [ ! -f /usr/local/lib/cmake/Drogon/DrogonConfig.cmake ] \
     && [ ! -f /usr/lib/cmake/Drogon/DrogonConfig.cmake ]; then
    echo "ERROR: Drogon not found (system or ${LOCAL_PREFIX})."
    echo "  On exabox, build the node-local deps once (no sudo, persists across nodes):"
    echo "    ./build_exabox.sh --install-deps   # installs Drogon/jsoncpp/uuid -> ${LOCAL_PREFIX}"
    echo "  Or system-wide (needs sudo): ./install_dependencies.sh"
    exit 1
fi

echo "=== Building C++ media server (--blaze) ==="
# shellcheck source=/dev/null
source "${PYTHON_ENV_DIR}/bin/activate"
"${SCRIPT_DIR}/build.sh" --blaze

cat <<EOF

==========================================================================
  Blaze build complete.
==========================================================================
Run the server with the real decode scheduler:

  export LD_LIBRARY_PATH="${TT_METAL_HOME}/build/lib:\${LD_LIBRARY_PATH:-}"
  LD_PRELOAD="${ENGINE_DIR}/build-full/libtt_llm_engine.so.0" \\
    ${SCRIPT_DIR}/build/tt_media_server_cpp

If Drogon / other deps live in a local prefix, prepend it too:
  export LD_LIBRARY_PATH="/data/\${USER}/.local/lib:\${LD_LIBRARY_PATH}"
EOF
