# SPDX-License-Identifier: Apache-2.0
#
# SPDX-FileCopyrightText: 2026 Tenstorrent AI ULC
"""Single-prompt sanity probe for a tt-inference-server local-server vLLM endpoint.

Lightweight standalone CLI that posts one chat-completion request and pretty-prints
the response with timing, token usage, and finish reason. Intended for quick
post-bring-up generation-quality checks without dragging in the heavyweight
benchmark client (tokenizer downloads, BatchProcessor, trace pre-capture, ...).

Auto-discovers the per-process VLLM_API_KEY by walking /proc/<EngineCore-pid>/environ
so the operator never has to copy the long JWT by hand. Falls back to
$VLLM_API_KEY, then to --no-auth-style anonymous request.

Examples:
    # Short prompt, auto key discovery
    python3 utils/local_server_prompt.py --prompt "Who is Albert Einstein?"

    # Long prompt from file, streaming output
    python3 utils/local_server_prompt.py --prompt-file /tmp/long_prompt.txt --stream

    # Specific model/url, raw JSON for piping into jq
    python3 utils/local_server_prompt.py --prompt "hi" \\
        --model inclusionAI/Ling-mini-2.0 \\
        --url http://127.0.0.1:8000 --json

Exit codes:
    0 - HTTP 200 with non-empty content
    1 - HTTP error or transport error
    2 - HTTP 200 but empty content (model produced nothing)
"""

from __future__ import annotations

import argparse
import json
import os
import subprocess
import sys
import time
from typing import Optional

import requests


DEFAULT_URL = "http://127.0.0.1:8000"
DEFAULT_MODEL = "inclusionAI/Ling-mini-2.0"
DEFAULT_MAX_TOKENS = 256
DEFAULT_TEMPERATURE = 0.7
DEFAULT_TOP_P = 0.9
REQUEST_TIMEOUT_SEC = 1800.0


def discover_api_key() -> Optional[str]:
    """Walk VLLM::EngineCore processes and pull VLLM_API_KEY out of /proc/<pid>/environ.

    Each EngineCore process gets a fresh API key generated by the local-server
    launcher. The key is exported into the EngineCore process environment, so we
    can read it back through the procfs even though it is not in our own env.

    Returns None if no EngineCore is running, the proc files are unreadable
    (different uid), or the env var is unset (e.g. server launched with
    --no-auth).
    """
    try:
        out = subprocess.check_output(
            ["pgrep", "-f", "VLLM::EngineCore"], stderr=subprocess.DEVNULL
        )
    except (subprocess.CalledProcessError, FileNotFoundError):
        return None

    for raw_pid in out.split():
        pid = raw_pid.decode().strip()
        if not pid.isdigit():
            continue
        try:
            with open(f"/proc/{pid}/environ", "rb") as fh:
                env = fh.read().split(b"\x00")
        except (FileNotFoundError, PermissionError):
            continue
        for kv in env:
            if kv.startswith(b"VLLM_API_KEY="):
                return kv.split(b"=", 1)[1].decode("utf-8", errors="replace")
    return None


def resolve_api_key(args: argparse.Namespace) -> Optional[str]:
    """Pick an API key in priority order: CLI flag > $VLLM_API_KEY > /proc lookup."""
    if args.no_auth:
        return None
    if args.api_key:
        return args.api_key
    env_key = os.environ.get("VLLM_API_KEY")
    if env_key:
        return env_key
    return discover_api_key()


def load_prompt(args: argparse.Namespace) -> str:
    if args.prompt is not None and args.prompt_file is not None:
        raise SystemExit("Specify exactly one of --prompt or --prompt-file, not both.")
    if args.prompt is not None:
        return args.prompt
    if args.prompt_file is not None:
        with open(args.prompt_file, "r", encoding="utf-8") as fh:
            return fh.read()
    if not sys.stdin.isatty():
        return sys.stdin.read()
    raise SystemExit("No prompt provided. Use --prompt, --prompt-file, or pipe stdin.")


def build_payload(prompt: str, args: argparse.Namespace) -> dict:
    messages = []
    if args.system:
        messages.append({"role": "system", "content": args.system})
    messages.append({"role": "user", "content": prompt})

    return {
        "model": args.model,
        "messages": messages,
        "max_tokens": args.max_tokens,
        "temperature": args.temperature,
        "top_p": args.top_p,
        "stream": bool(args.stream),
    }


def short(text: str, n: int = 100) -> str:
    """Truncate-with-ellipsis for inline log lines."""
    text = text.replace("\n", " ").replace("\r", " ")
    return text if len(text) <= n else text[: n - 3] + "..."


def post_streaming(
    chat_url: str, headers: dict, payload: dict
) -> tuple[int, str, Optional[str], int, float, float]:
    """Stream SSE response, printing tokens live. Returns
    (status_code, content, finish_reason, completion_tokens, ttft_sec, wall_sec).

    completion_tokens is the count of non-empty content deltas observed; this
    is approximate (it counts streaming chunks, not BPE tokens).
    """
    t0 = time.perf_counter()
    resp = requests.post(
        chat_url, headers=headers, json=payload, stream=True, timeout=REQUEST_TIMEOUT_SEC
    )
    ttft = 0.0
    chunks = 0
    content_parts: list[str] = []
    finish_reason: Optional[str] = None

    if resp.status_code != 200:
        body = resp.text
        return resp.status_code, body, None, 0, 0.0, time.perf_counter() - t0

    print("\n--- streaming output ---", flush=True)
    for line in resp.iter_lines(decode_unicode=True):
        if not line or not line.startswith("data: "):
            continue
        data_str = line[len("data: ") :].strip()
        if data_str == "[DONE]":
            break
        try:
            data = json.loads(data_str)
        except json.JSONDecodeError:
            continue
        choices = data.get("choices") or []
        if not choices:
            continue
        delta = choices[0].get("delta", {}) or {}
        piece = delta.get("content") or ""
        if piece:
            if chunks == 0:
                ttft = time.perf_counter() - t0
            chunks += 1
            content_parts.append(piece)
            sys.stdout.write(piece)
            sys.stdout.flush()
        if choices[0].get("finish_reason"):
            finish_reason = choices[0]["finish_reason"]

    sys.stdout.write("\n")
    sys.stdout.flush()
    wall = time.perf_counter() - t0
    return 200, "".join(content_parts), finish_reason, chunks, ttft, wall


def post_blocking(
    chat_url: str, headers: dict, payload: dict
) -> tuple[int, dict | str, float]:
    """Single non-streaming POST. Returns (status_code, parsed_json_or_text, wall_sec)."""
    t0 = time.perf_counter()
    resp = requests.post(
        chat_url, headers=headers, json=payload, timeout=REQUEST_TIMEOUT_SEC
    )
    wall = time.perf_counter() - t0
    if resp.status_code != 200:
        return resp.status_code, resp.text, wall
    try:
        return 200, resp.json(), wall
    except ValueError:
        return 200, resp.text, wall


def parse_args(argv: Optional[list[str]] = None) -> argparse.Namespace:
    p = argparse.ArgumentParser(
        prog="local_server_prompt",
        description=(
            "Send a single chat-completion to a tt-inference-server local-server "
            "vLLM endpoint and print the response with timing/usage stats."
        ),
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
    )
    src = p.add_mutually_exclusive_group()
    src.add_argument("--prompt", help="Inline prompt text.")
    src.add_argument(
        "--prompt-file",
        help="Read prompt text from this file (use for prompts longer than ~8 KB).",
    )
    p.add_argument(
        "--system",
        default=None,
        help="Optional system message prepended to the conversation.",
    )
    p.add_argument(
        "--max-tokens", type=int, default=DEFAULT_MAX_TOKENS,
        help="Maximum number of completion tokens to generate.",
    )
    p.add_argument(
        "--temperature", type=float, default=DEFAULT_TEMPERATURE,
        help="Sampling temperature.",
    )
    p.add_argument("--top-p", type=float, default=DEFAULT_TOP_P, help="Nucleus sampling p.")
    p.add_argument(
        "--model", default=DEFAULT_MODEL,
        help="Model id as registered by the server (matches /v1/models).",
    )
    p.add_argument(
        "--url", default=DEFAULT_URL,
        help="Base URL of the local server (without /v1).",
    )
    p.add_argument(
        "--api-key", default=None,
        help="Bearer token. If unset: $VLLM_API_KEY, else /proc auto-discovery.",
    )
    p.add_argument(
        "--no-auth", action="store_true",
        help="Send request without an Authorization header (for --no-auth servers).",
    )
    p.add_argument(
        "--stream", action="store_true",
        help="Stream tokens via SSE and print them as they arrive.",
    )
    p.add_argument(
        "--json", action="store_true",
        help="Print only the raw JSON response (non-streaming mode only).",
    )
    return p.parse_args(argv)


def main(argv: Optional[list[str]] = None) -> int:
    args = parse_args(argv)
    prompt = load_prompt(args)
    api_key = resolve_api_key(args)
    headers = {"Content-Type": "application/json"}
    if api_key:
        headers["Authorization"] = f"Bearer {api_key}"

    chat_url = args.url.rstrip("/") + "/v1/chat/completions"
    payload = build_payload(prompt, args)

    if not args.json and not args.stream:
        print(
            f"POST {chat_url}\n"
            f"  model={args.model}  max_tokens={args.max_tokens}  "
            f"temperature={args.temperature}  top_p={args.top_p}\n"
            f"  auth={'bearer' if api_key else 'anonymous'}  "
            f"prompt_chars={len(prompt)}  prompt_preview={short(prompt)!r}",
            flush=True,
        )

    if args.stream:
        status, content, finish_reason, chunks, ttft, wall = post_streaming(
            chat_url, headers, payload
        )
        if status != 200:
            print(f"\nHTTP {status}\n{content}", file=sys.stderr)
            return 1
        if not content:
            print("\nWARN: empty content", file=sys.stderr)
            return 2
        tps = chunks / max(wall - ttft, 1e-6) if chunks > 1 else 0.0
        print(
            f"\n--- summary ---\n"
            f"HTTP 200  finish_reason={finish_reason}\n"
            f"wall={wall:.2f}s  ttft={ttft:.2f}s  "
            f"stream_chunks={chunks}  approx_tps={tps:.2f}",
            flush=True,
        )
        return 0

    status, body, wall = post_blocking(chat_url, headers, payload)
    if status != 200:
        print(f"HTTP {status}\n{body}", file=sys.stderr)
        return 1

    if args.json:
        print(json.dumps(body, indent=2, ensure_ascii=False))
        choices = (body or {}).get("choices") or []
        content_check = choices[0].get("message", {}).get("content", "") if choices else ""
        return 0 if content_check else 2

    if not isinstance(body, dict):
        print(f"unexpected response body (not JSON):\n{body}", file=sys.stderr)
        return 1

    choices = body.get("choices") or []
    if not choices:
        print(f"HTTP 200 but no choices in response:\n{body}", file=sys.stderr)
        return 2
    message = choices[0].get("message") or {}
    content = message.get("content") or ""
    finish_reason = choices[0].get("finish_reason")
    usage = body.get("usage") or {}
    pt = usage.get("prompt_tokens")
    ct = usage.get("completion_tokens")
    tt = usage.get("total_tokens")

    print("\n--- response ---")
    print(content)
    print("\n--- summary ---")
    print(f"HTTP 200  finish_reason={finish_reason}")
    print(
        f"wall={wall:.2f}s  prompt_tokens={pt}  completion_tokens={ct}  total_tokens={tt}"
    )
    if ct and wall > 0:
        # Aggregate tps; with non-streaming we can't separate TTFT, so this
        # is an effective generation throughput across the full request.
        print(f"effective_tps={ct / wall:.2f}")
    return 0 if content else 2


if __name__ == "__main__":
    sys.exit(main())
