model: Llama-3.1-70B
device: galaxy
image:
  repository: ghcr.io/tenstorrent/tt-inference-server/vllm-tt-metal-src-release-ubuntu-22.04-amd64
  tag: 0.10.0-e867533-8f36910
resources:
  limits:
    memory: 256Gi
  requests:
    memory: 175Gi
probes:
  liveness:
    initialDelaySeconds: 5400   # ~90 min warmup on first run (70B model)
    periodSeconds: 30
  readiness:
    initialDelaySeconds: 5400
    periodSeconds: 10
