model: Llama-3.1-8B-Instruct
device: galaxy
image:
  repository: ghcr.io/tenstorrent/tt-inference-server/vllm-tt-metal-src-release-ubuntu-22.04-amd64
  tag: 0.11.1-bac8b34-7c6685a
resources:
  limits:
    memory: 32Gi
  requests:
    memory: 20Gi
probes:
  liveness:
    initialDelaySeconds: 2400   # ~40 min warmup on first run
    periodSeconds: 30
  readiness:
    initialDelaySeconds: 2400
    periodSeconds: 10
