model: stable-diffusion-xl-base-1.0
device: galaxy
serverType: media
image:
  repository: ghcr.io/tenstorrent/tt-media-inference-server
  tag: 0.10.0-555f240
resources:
  limits:
    memory: 480Gi
  requests:
    memory: 200Gi
probes:
  liveness:
    enabled: false
  readiness:
    enabled: false
