# SPDX-License-Identifier: Apache-2.0
#
# SPDX-FileCopyrightText: © 2025 Tenstorrent AI ULC
# config files for setup

model_config = {
    "DeepSeek-R1-Distill-Llama-70B": {
        "HF_MODEL_REPO_ID": "deepseek-ai/DeepSeek-R1-Distill-Llama-70B",
        "IMPL_ID": "tt-metal",
        "MIN_DISK": 350,
        "MIN_RAM": 350,
        "MODEL_NAME": "DeepSeek-R1-Distill-Llama-70B",
        "REPACKED": 0,
    },
    "Qwen2.5-72B": {
        "HF_MODEL_REPO_ID": "Qwen/Qwen2.5-72B",
        "IMPL_ID": "tt-metal",
        "MIN_DISK": 360,
        "MIN_RAM": 360,
        "MODEL_NAME": "Qwen2.5-72B",
        "REPACKED": 0,
    },
    "Qwen2.5-72B-Instruct": {
        "HF_MODEL_REPO_ID": "Qwen/Qwen2.5-72B-Instruct",
        "IMPL_ID": "tt-metal",
        "MIN_DISK": 360,
        "MIN_RAM": 360,
        "MODEL_NAME": "Qwen2.5-72B-Instruct",
        "REPACKED": 0,
    },
    "Qwen2.5-7B": {
        "HF_MODEL_REPO_ID": "Qwen/Qwen2.5-7B",
        "IMPL_ID": "tt-metal",
        "MIN_DISK": 28,
        "MIN_RAM": 35,
        "MODEL_NAME": "Qwen2.5-7B",
        "REPACKED": 0,
    },
    "Qwen2.5-7B-Instruct": {
        "HF_MODEL_REPO_ID": "Qwen/Qwen2.5-7B-Instruct",
        "IMPL_ID": "tt-metal",
        "MIN_DISK": 28,
        "MIN_RAM": 35,
        "MODEL_NAME": "Qwen2.5-7B-Instruct",
        "REPACKED": 0,
    },
    "Llama-3.3-70B": {
        "HF_MODEL_REPO_ID": "meta-llama/Llama-3.3-70B",
        "IMPL_ID": "tt-metal",
        "MIN_DISK": 350,
        "MIN_RAM": 350,
        "MODEL_NAME": "Llama-3.3-70B",
        "REPACKED": 1,
    },
    "Llama-3.3-70B-Instruct": {
        "HF_MODEL_REPO_ID": "meta-llama/Llama-3.3-70B-Instruct",
        "IMPL_ID": "tt-metal",
        "MIN_DISK": 350,
        "MIN_RAM": 350,
        "MODEL_NAME": "Llama-3.3-70B-Instruct",
        "REPACKED": 1,
    },
    "Llama-3.2-11B-Vision": {
        "HF_MODEL_REPO_ID": "meta-llama/Llama-3.2-11B-Vision",
        "IMPL_ID": "tt-metal",
        "MIN_DISK": 44,
        "MIN_RAM": 55,
        "MODEL_NAME": "Llama-3.2-11B-Vision",
        "REPACKED": 0,
    },
    "Llama-3.2-11B-Vision-Instruct": {
        "HF_MODEL_REPO_ID": "meta-llama/Llama-3.2-11B-Vision-Instruct",
        "IMPL_ID": "tt-metal",
        "MIN_DISK": 44,
        "MIN_RAM": 55,
        "MODEL_NAME": "Llama-3.2-11B-Vision-Instruct",
        "REPACKED": 0,
    },
    "Llama-3.2-1B": {
        "HF_MODEL_REPO_ID": "meta-llama/Llama-3.2-1B",
        "IMPL_ID": "tt-metal",
        "MIN_DISK": 4,
        "MIN_RAM": 5,
        "MODEL_NAME": "Llama-3.2-1B",
        "REPACKED": 0,
    },
    "Llama-3.2-1B-Instruct": {
        "HF_MODEL_REPO_ID": "meta-llama/Llama-3.2-1B-Instruct",
        "IMPL_ID": "tt-metal",
        "MIN_DISK": 4,
        "MIN_RAM": 5,
        "MODEL_NAME": "Llama-3.2-1B-Instruct",
        "REPACKED": 0,
    },
    "Llama-3.2-3B": {
        "HF_MODEL_REPO_ID": "meta-llama/Llama-3.2-3B",
        "IMPL_ID": "tt-metal",
        "MIN_DISK": 12,
        "MIN_RAM": 15,
        "MODEL_NAME": "Llama-3.2-3B",
        "REPACKED": 0,
    },
    "Llama-3.2-3B-Instruct": {
        "HF_MODEL_REPO_ID": "meta-llama/Llama-3.2-3B-Instruct",
        "IMPL_ID": "tt-metal",
        "MIN_DISK": 12,
        "MIN_RAM": 15,
        "MODEL_NAME": "Llama-3.2-3B-Instruct",
        "REPACKED": 0,
    },
    "Llama-3.1-70B": {
        "HF_MODEL_REPO_ID": "meta-llama/Llama-3.1-70B",
        "IMPL_ID": "tt-metal",
        "MIN_DISK": 350,
        "MIN_RAM": 350,
        "MODEL_NAME": "Llama-3.1-70B",
        "REPACKED": 1,
    },
    "Llama-3.1-70B-Instruct": {
        "HF_MODEL_REPO_ID": "meta-llama/Llama-3.1-70B-Instruct",
        "IMPL_ID": "tt-metal",
        "MIN_DISK": 350,
        "MIN_RAM": 350,
        "MODEL_NAME": "Llama-3.1-70B-Instruct",
        "REPACKED": 1,
    },
    "Llama-3.1-8B": {
        "HF_MODEL_REPO_ID": "meta-llama/Llama-3.1-8B",
        "IMPL_ID": "tt-metal",
        "MIN_DISK": 32,
        "MIN_RAM": 40,
        "MODEL_NAME": "Llama-3.1-8B",
        "REPACKED": 0,
    },
    "Llama-3.1-8B-Instruct": {
        "HF_MODEL_REPO_ID": "meta-llama/Llama-3.1-8B-Instruct",
        "IMPL_ID": "tt-metal",
        "MIN_DISK": 32,
        "MIN_RAM": 40,
        "MODEL_NAME": "Llama-3.1-8B-Instruct",
        "REPACKED": 0,
    },
    "Llama-3-70B": {
        "HF_MODEL_REPO_ID": "meta-llama/Llama-3-70B",
        "IMPL_ID": "tt-metal",
        "MIN_DISK": 350,
        "MIN_RAM": 350,
        "MODEL_NAME": "Llama-3-70B",
        "REPACKED": 1,
    },
    "Llama-3-70B-Instruct": {
        "HF_MODEL_REPO_ID": "meta-llama/Llama-3-70B-Instruct",
        "IMPL_ID": "tt-metal",
        "MIN_DISK": 350,
        "MIN_RAM": 350,
        "MODEL_NAME": "Llama-3-70B-Instruct",
        "REPACKED": 1,
    },
    "Llama-3-8B": {
        "HF_MODEL_REPO_ID": "meta-llama/Llama-3-8B",
        "IMPL_ID": "tt-metal",
        "MIN_DISK": 32,
        "MIN_RAM": 40,
        "MODEL_NAME": "Llama-3-8B",
        "REPACKED": 0,
    },
    "Llama-3-8B-Instruct": {
        "HF_MODEL_REPO_ID": "meta-llama/Llama-3-8B-Instruct",
        "IMPL_ID": "tt-metal",
        "MIN_DISK": 32,
        "MIN_RAM": 40,
        "MODEL_NAME": "Llama-3-8B-Instruct",
        "REPACKED": 0,
    },
}
