apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: llama-3.3-70b-instruct-galaxy-
resources:
  - ../../base/vllm
images:
  - name: ghcr.io/tenstorrent/tt-inference-server/vllm-tt-metal-src-release-ubuntu-22.04-amd64
    newTag: 0.10.0-e867533-8f36910
patches:
  - path: patch-deployment.yaml
secretGenerator:
  - name: tt-inference-server
    envs:
      - ../../hf-token.env
    options:
      disableNameSuffixHash: true
