name: SPDX header checker

on:
  workflow_dispatch:
  workflow_call:
  pull_request:
    branches:
      - "main"

jobs:
  run-spdx-header-script:
    runs-on: ubuntu-20.04
    steps:
      # Checkout the repository
      - uses: actions/checkout@v4

      # Set up Python
      - uses: actions/setup-python@v5.0.0
        with:
          python-version: "3.8"

      # Run the `add_spdx_header.py` script to add SPDX headers to all files
      - name: Run SPDX Header Script
        run: |
          echo "Running SPDX header script on all files in the repository"
          python ./scripts/add_spdx_header.py

      # Commit the changes 
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_user_name: SPDX-Bot
          commit_user_email: bot@example.com
          commit_message: '🚨✨AUTOMATED COMMIT | Added missing SPDX license headers automatically'
          branch: ${{ github.head_ref }}
